### ISSUE TITLE
Cannot draw dot

### ISSUE THREAD

**Issue by minawk** [kiwi-bop/flutter_signature_pad#15]
I can't make a dot point.
Update:
* Pull Request: [https://github.com/kiwi-bop/flutter_signature_pad/pull/16](url)

**Comment by jaumard** [comment]
Published as 2.0.1 :) Thanks for the PR !

**Comment by TarikHuber** [comment]
Are additional properties need to enable drawing dots?
I'm currently using the version 2.0.2 on Android and still can't draw a dot.

**Comment by raymondnexsoftech** [comment]
I found that the problem is from the commit "https://github.com/kiwi-bop/flutter_signature_pad/commit/64644398bd871251ecd41a0befcea3fab6afb54b" that implementing the "onVerticalDrag" series.
After adding Vertical Drag detection, Flutter will have a delay to recognize the gesture is signing. That's why the dot is not working.
For workaround, if you are not placing the signature inside the scrollview, you may download the plugin as local plugin and disable the "onVerticalDrag" series to solve the problem.
